# docker-compose.yml
# https://devops.tutorials24x7.com/blog/containerize-php-with-apache-mysql-and-mongodb-using-docker-containers
# https://www.youtube.com/watch?v=yyJjHsnWow8&list=PLoRfWwOOv4jws0vY3LqnztFlf6OddUJg8
# https://www.youtube.com/watch?v=CV_Uf3Dq-EU
version: "3.8"
services:
  # configuracion del servicio apache
  apache:
    container_name: apache
    build: ./docker/apache
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ./src:/usr/local/apache2/htdocs
  # configuracion del servicio php
  php:
    container_name: php
    build: ./docker/php
    links:
      - mysql
      - mongo
    ports:
      - "9000:9000"
    volumes:
      - ./src:/usr/local/apache2/htdocs
    working_dir: /usr/local/apache2/htdocs
  # configuracion del servicio mysql
  mysql:
    image: mysql
    container_name: mysql
    environment:
      # MYSQL_ROOT_NAME: root
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: tnsql
      MYSQL_USER: tnsql
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
  # configuracion del servicio phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8085:80
  # configuracion del servicio mongo
  mongo:
    # docker pull mongo:7.0.2
    image: mongo
    container_name: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongodb/db:/data/db
      - ./database/mongodb/dev.archive:/Databases/dev.archive
      - ./database/mongodb/production:/Databases/production
  # configuracion del servicio mongo-express
  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"